// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/go-containerregistry/pkg/v1 (interfaces: Image)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	v1 "github.com/google/go-containerregistry/pkg/v1"
	types "github.com/google/go-containerregistry/pkg/v1/types"
	reflect "reflect"
)

// MockV1Image is a mock of Image interface
type MockV1Image struct {
	ctrl     *gomock.Controller
	recorder *MockV1ImageMockRecorder
}

// MockV1ImageMockRecorder is the mock recorder for MockV1Image
type MockV1ImageMockRecorder struct {
	mock *MockV1Image
}

// NewMockV1Image creates a new mock instance
func NewMockV1Image(ctrl *gomock.Controller) *MockV1Image {
	mock := &MockV1Image{ctrl: ctrl}
	mock.recorder = &MockV1ImageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockV1Image) EXPECT() *MockV1ImageMockRecorder {
	return m.recorder
}

// BlobSet mocks base method
func (m *MockV1Image) BlobSet() (map[v1.Hash]struct{}, error) {
	ret := m.ctrl.Call(m, "BlobSet")
	ret0, _ := ret[0].(map[v1.Hash]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlobSet indicates an expected call of BlobSet
func (mr *MockV1ImageMockRecorder) BlobSet() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobSet", reflect.TypeOf((*MockV1Image)(nil).BlobSet))
}

// ConfigFile mocks base method
func (m *MockV1Image) ConfigFile() (*v1.ConfigFile, error) {
	ret := m.ctrl.Call(m, "ConfigFile")
	ret0, _ := ret[0].(*v1.ConfigFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfigFile indicates an expected call of ConfigFile
func (mr *MockV1ImageMockRecorder) ConfigFile() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigFile", reflect.TypeOf((*MockV1Image)(nil).ConfigFile))
}

// ConfigName mocks base method
func (m *MockV1Image) ConfigName() (v1.Hash, error) {
	ret := m.ctrl.Call(m, "ConfigName")
	ret0, _ := ret[0].(v1.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfigName indicates an expected call of ConfigName
func (mr *MockV1ImageMockRecorder) ConfigName() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigName", reflect.TypeOf((*MockV1Image)(nil).ConfigName))
}

// Digest mocks base method
func (m *MockV1Image) Digest() (v1.Hash, error) {
	ret := m.ctrl.Call(m, "Digest")
	ret0, _ := ret[0].(v1.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Digest indicates an expected call of Digest
func (mr *MockV1ImageMockRecorder) Digest() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Digest", reflect.TypeOf((*MockV1Image)(nil).Digest))
}

// LayerByDiffID mocks base method
func (m *MockV1Image) LayerByDiffID(arg0 v1.Hash) (v1.Layer, error) {
	ret := m.ctrl.Call(m, "LayerByDiffID", arg0)
	ret0, _ := ret[0].(v1.Layer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LayerByDiffID indicates an expected call of LayerByDiffID
func (mr *MockV1ImageMockRecorder) LayerByDiffID(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LayerByDiffID", reflect.TypeOf((*MockV1Image)(nil).LayerByDiffID), arg0)
}

// LayerByDigest mocks base method
func (m *MockV1Image) LayerByDigest(arg0 v1.Hash) (v1.Layer, error) {
	ret := m.ctrl.Call(m, "LayerByDigest", arg0)
	ret0, _ := ret[0].(v1.Layer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LayerByDigest indicates an expected call of LayerByDigest
func (mr *MockV1ImageMockRecorder) LayerByDigest(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LayerByDigest", reflect.TypeOf((*MockV1Image)(nil).LayerByDigest), arg0)
}

// Layers mocks base method
func (m *MockV1Image) Layers() ([]v1.Layer, error) {
	ret := m.ctrl.Call(m, "Layers")
	ret0, _ := ret[0].([]v1.Layer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Layers indicates an expected call of Layers
func (mr *MockV1ImageMockRecorder) Layers() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Layers", reflect.TypeOf((*MockV1Image)(nil).Layers))
}

// Manifest mocks base method
func (m *MockV1Image) Manifest() (*v1.Manifest, error) {
	ret := m.ctrl.Call(m, "Manifest")
	ret0, _ := ret[0].(*v1.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Manifest indicates an expected call of Manifest
func (mr *MockV1ImageMockRecorder) Manifest() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manifest", reflect.TypeOf((*MockV1Image)(nil).Manifest))
}

// MediaType mocks base method
func (m *MockV1Image) MediaType() (types.MediaType, error) {
	ret := m.ctrl.Call(m, "MediaType")
	ret0, _ := ret[0].(types.MediaType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MediaType indicates an expected call of MediaType
func (mr *MockV1ImageMockRecorder) MediaType() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MediaType", reflect.TypeOf((*MockV1Image)(nil).MediaType))
}

// RawConfigFile mocks base method
func (m *MockV1Image) RawConfigFile() ([]byte, error) {
	ret := m.ctrl.Call(m, "RawConfigFile")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawConfigFile indicates an expected call of RawConfigFile
func (mr *MockV1ImageMockRecorder) RawConfigFile() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawConfigFile", reflect.TypeOf((*MockV1Image)(nil).RawConfigFile))
}

// RawManifest mocks base method
func (m *MockV1Image) RawManifest() ([]byte, error) {
	ret := m.ctrl.Call(m, "RawManifest")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawManifest indicates an expected call of RawManifest
func (mr *MockV1ImageMockRecorder) RawManifest() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawManifest", reflect.TypeOf((*MockV1Image)(nil).RawManifest))
}
