// Vendored from https://github.com/moby/moby/blob/e01269424ec0db6509c9937ff891f0a9ab7a0884/daemon/volume/mounts/mounts.go
// Hand-reduced to the parsing subset -- NOT regenerated by
// tools/vendor-volume-mounts.sh. See internal/volume/VENDORED.txt before editing.

package volume

import (
	mounttypes "github.com/moby/moby/api/types/mount"
	"github.com/pkg/errors"
)

// MountPoint is the intersection point between a volume and a container. It
// specifies which volume is to be used and where inside a container it should
// be mounted.
//
// Upstream this type also carries the daemon-side state needed to actually
// perform the mount. pack only ever parses mount specs, so the fields below are
// the ones the parsers populate; Volume, ID, SkipMountpointCreation, active,
// safePaths and Layer are omitted along with Setup/Cleanup and the RWLayer
// interface. Dropping them is what keeps selinux, safepath, idtools and
// stringid out of pack's dependency graph.
type MountPoint struct {
	// Source is the source path of the mount.
	// E.g. `mount --bind /foo /bar`, `/foo` is the `Source`.
	Source string
	// Destination is the path relative to the container root (`/`) to the mount point
	// It is where the `Source` is mounted to
	Destination string
	// RW is set to true when the mountpoint should be mounted as read-write
	RW bool
	// Name is the name reference to the underlying data defined by `Source`
	// e.g., the volume name
	Name string
	// Driver is the volume driver used to create the volume (if it is a volume)
	Driver string
	// Type of mount to use.
	Type mounttypes.Type `json:",omitempty"`

	// Mode is the comma separated list of options supplied by the user when creating
	// the bind/volume mount.
	// Note Mode is not used on Windows
	Mode string `json:"Relabel,omitempty"` // Originally field was `Relabel`"

	// Propagation describes how the mounts are propagated from the host into the
	// mount point, and vice-versa.
	// See https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt
	// Note Propagation is not used on Windows
	Propagation mounttypes.Propagation `json:",omitempty"` // Mount propagation string

	// Specifies if data should be copied from the container before the first mount
	// Use a pointer here so we can tell if the user set this value explicitly
	// This allows us to error out when the user explicitly enabled copy but we can't copy due to the volume being populated
	CopyData bool `json:"-"`

	// Spec is a copy of the API request that created this mount.
	Spec mounttypes.Mount
}

// Path returns the path of the mount source.
//
// Upstream this first consults m.Volume, which is unreachable here: nothing in
// pack populates that field, so the source path is always the answer.
func (m *MountPoint) Path() string {
	return m.Source
}

func errInvalidMode(mode string) error {
	return errors.Errorf("invalid mode: %v", mode)
}

func errInvalidSpec(spec string) error {
	return errors.Errorf("invalid volume specification: '%s'", spec)
}
