// Vendored from https://github.com/moby/moby/blob/e01269424ec0db6509c9937ff891f0a9ab7a0884/daemon/volume/mounts/volume_copy.go
// Generated by tools/vendor-volume-mounts.sh -- do not edit by hand.
// Local modifications are listed in internal/volume/VENDORED.txt.

package volume

import "strings"

// {<copy mode>=isEnabled}
var copyModes = map[string]bool{
	"nocopy": false,
}

func copyModeExists(mode string) bool {
	_, exists := copyModes[mode]
	return exists
}

// GetCopyMode gets the copy mode from the mode string for mounts
func getCopyMode(mode string, def bool) (bool, bool) {
	for o := range strings.SplitSeq(mode, ",") {
		if isEnabled, exists := copyModes[o]; exists {
			return isEnabled, true
		}
	}
	return def, false
}
