// Vendored from https://github.com/moby/moby/blob/e01269424ec0db6509c9937ff891f0a9ab7a0884/daemon/volume/mounts/volume_unix.go
// Generated by tools/vendor-volume-mounts.sh -- do not edit by hand.
// Local modifications are listed in internal/volume/VENDORED.txt.

//go:build linux || freebsd || darwin

package volume

import (
	"fmt"
	"path/filepath"
	"strings"
)

func (p *linuxParser) HasResource(m *MountPoint, absolutePath string) bool {
	relPath, err := filepath.Rel(m.Destination, absolutePath)
	return err == nil && relPath != ".." && !strings.HasPrefix(relPath, fmt.Sprintf("..%c", filepath.Separator))
}
