// Vendored from https://github.com/moby/moby/blob/e01269424ec0db6509c9937ff891f0a9ab7a0884/daemon/volume/mounts/volume_windows.go
// Generated by tools/vendor-volume-mounts.sh -- do not edit by hand.
// Local modifications are listed in internal/volume/VENDORED.txt.

package volume

func (p *linuxParser) HasResource(m *MountPoint, absolutePath string) bool {
	return false
}
