// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/buildpacks/pack/internal/builder (interfaces: AssetLayerWriter)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	asset "github.com/buildpacks/pack/internal/asset"
	dist "github.com/buildpacks/pack/internal/dist"
)

// MockAssetLayerWriter is a mock of AssetLayerWriter interface
type MockAssetLayerWriter struct {
	ctrl     *gomock.Controller
	recorder *MockAssetLayerWriterMockRecorder
}

// MockAssetLayerWriterMockRecorder is the mock recorder for MockAssetLayerWriter
type MockAssetLayerWriterMockRecorder struct {
	mock *MockAssetLayerWriter
}

// NewMockAssetLayerWriter creates a new mock instance
func NewMockAssetLayerWriter(ctrl *gomock.Controller) *MockAssetLayerWriter {
	mock := &MockAssetLayerWriter{ctrl: ctrl}
	mock.recorder = &MockAssetLayerWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAssetLayerWriter) EXPECT() *MockAssetLayerWriterMockRecorder {
	return m.recorder
}

// AddAssetBlobs mocks base method
func (m *MockAssetLayerWriter) AddAssetBlobs(arg0 ...asset.Blob) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddAssetBlobs", varargs...)
}

// AddAssetBlobs indicates an expected call of AddAssetBlobs
func (mr *MockAssetLayerWriterMockRecorder) AddAssetBlobs(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAssetBlobs", reflect.TypeOf((*MockAssetLayerWriter)(nil).AddAssetBlobs), arg0...)
}

// AssetMetadata mocks base method
func (m *MockAssetLayerWriter) AssetMetadata() dist.AssetMap {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssetMetadata")
	ret0, _ := ret[0].(dist.AssetMap)
	return ret0
}

// AssetMetadata indicates an expected call of AssetMetadata
func (mr *MockAssetLayerWriterMockRecorder) AssetMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssetMetadata", reflect.TypeOf((*MockAssetLayerWriter)(nil).AssetMetadata))
}

// Close mocks base method
func (m *MockAssetLayerWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockAssetLayerWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAssetLayerWriter)(nil).Close))
}

// Open mocks base method
func (m *MockAssetLayerWriter) Open() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open")
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open
func (mr *MockAssetLayerWriterMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockAssetLayerWriter)(nil).Open))
}

// Write mocks base method
func (m *MockAssetLayerWriter) Write(arg0 asset.Writable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write
func (mr *MockAssetLayerWriterMockRecorder) Write(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockAssetLayerWriter)(nil).Write), arg0)
}
