// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/buildpacks/pack/internal/builder (interfaces: AssetLayerReader)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	asset "github.com/buildpacks/pack/internal/asset"
	dist "github.com/buildpacks/pack/internal/dist"
)

// MockAssetLayerReader is a mock of AssetLayerReader interface
type MockAssetLayerReader struct {
	ctrl     *gomock.Controller
	recorder *MockAssetLayerReaderMockRecorder
}

// MockAssetLayerReaderMockRecorder is the mock recorder for MockAssetLayerReader
type MockAssetLayerReaderMockRecorder struct {
	mock *MockAssetLayerReader
}

// NewMockAssetLayerReader creates a new mock instance
func NewMockAssetLayerReader(ctrl *gomock.Controller) *MockAssetLayerReader {
	mock := &MockAssetLayerReader{ctrl: ctrl}
	mock.recorder = &MockAssetLayerReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAssetLayerReader) EXPECT() *MockAssetLayerReaderMockRecorder {
	return m.recorder
}

// Read mocks base method
func (m *MockAssetLayerReader) Read(arg0 asset.Readable) ([]asset.Blob, dist.AssetMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].([]asset.Blob)
	ret1, _ := ret[1].(dist.AssetMap)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Read indicates an expected call of Read
func (mr *MockAssetLayerReaderMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockAssetLayerReader)(nil).Read), arg0)
}
