#!/usr/bin/env bash
#
# Re-vendors the mount-spec parser from github.com/moby/moby into
# internal/volume.
#
# pack only needs to parse `--volume` specs. The upstream package lives inside
# the daemon and drags in selinux, safepath and several moby-internal packages,
# so we vendor the parser rather than depend on the deprecated
# github.com/docker/docker module. See internal/volume/VENDORED.txt.
#
# Usage:
#   tools/vendor-volume-mounts.sh            # re-vendor in place
#   tools/vendor-volume-mounts.sh --check    # fail if the tree has drifted
#
# To bump to a newer upstream revision, change UPSTREAM_SHA/UPSTREAM_DATE below
# and re-run. mounts.go is NOT regenerated -- see the note at the bottom.

set -euo pipefail

UPSTREAM_REPO="moby/moby"
UPSTREAM_PATH="daemon/volume/mounts"
UPSTREAM_SHA="e01269424ec0db6509c9937ff891f0a9ab7a0884"
UPSTREAM_DATE="2026-07-20"

# Files regenerated mechanically from upstream. mounts.go is excluded on
# purpose: it is hand-reduced to the parsing subset (see below).
FILES=(
  lcow_parser.go
  linux_parser.go
  parser.go
  validate.go
  volume_copy.go
  volume_unix.go
  volume_windows.go
  windows_parser.go
)

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${REPO_ROOT}/internal/volume"

check_mode=false
[[ "${1:-}" == "--check" ]] && check_mode=true

# goimports re-adds the stdlib regexp import that the lazyregexp substitution
# introduces, so it is required rather than a nicety.
GOIMPORTS="$(command -v goimports || true)"
if [[ -z "${GOIMPORTS}" ]] && [[ -x "$(go env GOPATH)/bin/goimports" ]]; then
  GOIMPORTS="$(go env GOPATH)/bin/goimports"
fi
if [[ -z "${GOIMPORTS}" ]]; then
  echo "error: goimports not found; run 'make format' once or 'go install golang.org/x/tools/cmd/goimports@latest'" >&2
  exit 1
fi

workdir="$(mktemp -d)"
trap 'rm -rf "${workdir}"' EXIT

for f in "${FILES[@]}"; do
  url="https://raw.githubusercontent.com/${UPSTREAM_REPO}/${UPSTREAM_SHA}/${UPSTREAM_PATH}/${f}"
  curl -sfL "${url}" -o "${workdir}/${f}" \
    || { echo "error: could not fetch ${url}" >&2; exit 1; }

  # Local modifications, all mechanical. Keep this list in sync with
  # internal/volume/VENDORED.txt.
  #
  #  1. package mounts -> package volume
  #  2. drop moby-internal lazyregexp in favour of the stdlib regexp
  #  3. drop the daemon/volume import; DefaultDriverName is the string "local"
  sed -i.bak \
    -e 's|^package mounts$|package volume|' \
    -e '\|"github.com/moby/moby/v2/daemon/internal/lazyregexp"|d' \
    -e '\|"github.com/moby/moby/v2/daemon/volume"|d' \
    -e 's|lazyregexp\.New(|regexp.MustCompile(|g' \
    -e 's|\*lazyregexp\.Regexp|*regexp.Regexp|g' \
    -e 's|volume\.DefaultDriverName|"local"|g' \
    "${workdir}/${f}"
  rm -f "${workdir}/${f}.bak"

  # Provenance header. Placed before any //go:build line so the constraint is
  # still preceded only by comments and blank lines, and separated from the
  # package clause so it does not become a duplicated package doc comment.
  cat > "${workdir}/${f}.hdr" <<EOF
// Vendored from https://github.com/${UPSTREAM_REPO}/blob/${UPSTREAM_SHA}/${UPSTREAM_PATH}/${f}
// Generated by tools/vendor-volume-mounts.sh -- do not edit by hand.
// Local modifications are listed in internal/volume/VENDORED.txt.

EOF
  cat "${workdir}/${f}" >> "${workdir}/${f}.hdr"
  mv "${workdir}/${f}.hdr" "${workdir}/${f}"

  # goimports re-adds "regexp" where the substitution above introduced it and
  # restores pack's import grouping.
  "${GOIMPORTS}" -w -local github.com/buildpacks/pack "${workdir}/${f}"
done

if [[ "${check_mode}" == true ]]; then
  status=0
  for f in "${FILES[@]}"; do
    if ! diff -u "${DEST}/${f}" "${workdir}/${f}" > /dev/null; then
      echo "drift: internal/volume/${f} differs from ${UPSTREAM_REPO}@${UPSTREAM_SHA}" >&2
      diff -u "${DEST}/${f}" "${workdir}/${f}" >&2 || true
      status=1
    fi
  done
  if [[ "${status}" -eq 0 ]]; then
    echo "internal/volume matches ${UPSTREAM_REPO}@${UPSTREAM_SHA} (${UPSTREAM_DATE})"
  fi
  exit "${status}"
fi

for f in "${FILES[@]}"; do
  cp "${workdir}/${f}" "${DEST}/${f}"
done

cat > "${DEST}/VENDORED.txt" <<EOF
Vendored from: https://github.com/${UPSTREAM_REPO}
Upstream path: https://github.com/${UPSTREAM_REPO}/tree/${UPSTREAM_SHA}/${UPSTREAM_PATH}
Commit SHA:    ${UPSTREAM_SHA}
Commit date:   ${UPSTREAM_DATE}
License:       Apache License 2.0 -- see internal/volume/LICENSE

Regenerate with: tools/vendor-volume-mounts.sh
Verify with:     tools/vendor-volume-mounts.sh --check

Why this is vendored
--------------------
pack only needs to parse '--volume' specs. Upstream this parser lives inside
the daemon and pulls in github.com/opencontainers/selinux, daemon/volume/safepath
(and through it cyphar.com/go-pathrs) plus several moby-internal packages. Taking
it as a dependency meant keeping the deprecated github.com/docker/docker module.

Local modifications
-------------------
Applied mechanically by tools/vendor-volume-mounts.sh:

  1. 'package mounts' becomes 'package volume'.
  2. github.com/moby/moby/v2/daemon/internal/lazyregexp is moby-internal and not
     importable, so lazyregexp.New becomes regexp.MustCompile from the stdlib.
     The regexps are compiled at init rather than on first use; there are seven
     of them and they are all used on the parse path.
  3. github.com/moby/moby/v2/daemon/volume is dropped; volume.DefaultDriverName
     is inlined as its value, the string "local".

Applied by hand, and NOT regenerated by the script:

  4. mounts.go is reduced to the parsing subset: the MountPoint fields the
     parsers populate, Path(), errInvalidMode() and errInvalidSpec(). The
     daemon-side surface is removed -- Setup/Cleanup, the RWLayer interface, and
     the Volume, ID, SkipMountpointCreation, active, safePaths and Layer fields.
     Those are what pull in selinux, safepath, idtools and stringid.
     MountPoint.Path() loses its m.Volume branch, which is unreachable here
     because nothing in pack ever populates that field.

Because mounts.go is hand-maintained, '--check' does not cover it. The weekly
drift workflow (.github/workflows/check-vendored-volume-mounts.yml) watches the
whole upstream directory, so a change to mounts.go still raises an issue; a human
then re-runs the script and reconciles mounts.go by hand.
EOF

echo "re-vendored internal/volume from ${UPSTREAM_REPO}@${UPSTREAM_SHA} (${UPSTREAM_DATE})"
