name: "PR"

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}


jobs:
  validate:
    permissions:
      contents: read
      pull-requests: read
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@1d8cd483a2b73118406a187f54dca8a9415f1375 # v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pr-title-checker-config.json"
